spring:
  application:
    name: demo
  # datasource:
  #   url: jdbc:mysql://localhost:3306/qinghai?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
  #   username: root
  #   password: ""
  #   driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    url: jdbc:postgresql://dpg-d8aop2gjs32c739cr3bg-a.oregon-postgres.render.com:5432/chen_ueeg?sslmode=require
    username: chen_ueeg_user
    password: Aj8z4cS7UWBhS238yZVDIv83OYmym8c
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
