spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://dpg-d8aop2gjs32c739cr3bg-a.oregon-postgres.render.com:5432/chen_ueeg?sslmode=require
    username: chen_ueeg_user
    password: A2j8z4cS7UWBhS238yZVDIv83OYmym8c
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: SET timezone = 'Asia/Shanghai'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/init.sql

server:
  port: ${PORT:8080}

# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
